<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.codesai.katas-java</groupId>
  <artifactId>katas-java-parent</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>argent-rose</module>
    <module>course-duration</module>
    <module>tire-pressure-variation</module>
    <module>breaking-dependencies/checkout-with-side-effects</module>
    <module>breaking-dependencies/problematic-discount</module>
    <module>breaking-dependencies/problematic-searcher</module>
    <module>ugly-trivia</module>
    <module>ugly-trivia-approval</module>
    <module>gilded-rose</module>
  </modules>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.openrewrite.maven</groupId>
          <artifactId>rewrite-maven-plugin</artifactId>
          <version>6.28.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

</project>
