package com.argentrose;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

// Generated by Junie powered by gpt-5-2025-08-07

public class ArgentRoseStoreTest {

    @Test
    @DisplayName("Regular product: sellIn decreases by 1 and quality decreases by 2 before expiry")
    void regular_before_expiry() {
        Product swordOil = new Product("Sword Oil", 10, 20);
        ArgentRoseStore store = new ArgentRoseStore(List.of(swordOil));

        store.updateEndOfDay();

        assertThat(swordOil.getSellIn()).isEqualTo(9);
        assertThat(swordOil.getQuality()).isEqualTo(18);
    }

    @Test
    @DisplayName("Regular product: after expiry quality decreases twice as fast (from 2 to 4 per day)")
    void regular_after_expiry_decreases_twice_as_fast() {
        Product herb = new Product("Common Herb", 0, 7);
        ArgentRoseStore store = new ArgentRoseStore(List.of(herb));

        store.updateEndOfDay();

        assertThat(herb.getSellIn()).isEqualTo(-1);
        assertThat(herb.getQuality()).isEqualTo(3); // 7 - 4
    }

    @Test
    @DisplayName("Quality never goes below 0")
    void quality_never_negative() {
        Product staleBread = new Product("Stale Bread", 0, 3);
        ArgentRoseStore store = new ArgentRoseStore(List.of(staleBread));

        store.updateEndOfDay();

        assertThat(staleBread.getSellIn()).isEqualTo(-1);
        assertThat(staleBread.getQuality()).isEqualTo(0);
    }

    @Test
    @DisplayName("Theatre Passes: increase by 1 when more than five days left")
    void theatre_passes_increase_by_one_above_five() {
        Product passes = new Product("Theatre Passes", 7, 10);
        ArgentRoseStore store = new ArgentRoseStore(List.of(passes));

        store.updateEndOfDay();

        assertThat(passes.getSellIn()).isEqualTo(6);
        assertThat(passes.getQuality()).isEqualTo(11);
    }

    @Test
    @DisplayName("Theatre Passes: increase by 3 when five days or less left")
    void theatre_passes_increase_by_three_at_five_or_less() {
        Product passes = new Product("Theatre Passes", 5, 10);
        ArgentRoseStore store = new ArgentRoseStore(List.of(passes));

        store.updateEndOfDay();

        assertThat(passes.getSellIn()).isEqualTo(4);
        assertThat(passes.getQuality()).isEqualTo(13);
    }

    @Test
    @DisplayName("Theatre Passes: drop to zero after the play (when expired)")
    void theatre_passes_drop_to_zero_after_play() {
        Product passes = new Product("Theatre Passes", 0, 25);
        ArgentRoseStore store = new ArgentRoseStore(List.of(passes));

        store.updateEndOfDay();

        assertThat(passes.getSellIn()).isEqualTo(-1);
        assertThat(passes.getQuality()).isEqualTo(0);
    }

    @Test
    @DisplayName("Quality is capped at 50 even when increases apply")
    void quality_capped_at_50() {
        Product passes = new Product("Theatre Passes", 5, 49);
        ArgentRoseStore store = new ArgentRoseStore(List.of(passes));

        store.updateEndOfDay();

        assertThat(passes.getSellIn()).isEqualTo(4);
        assertThat(passes.getQuality()).isEqualTo(50);
    }
}
