package com.argentrose;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

// Generated by Junie powered by gpt-5-2025-08-07

/**
 * Argent Rose store updates inventory daily following the provided specification.
 */
public class ArgentRoseStore {

    private final List<Product> products;

    public ArgentRoseStore(List<Product> products) {
        this.products = new ArrayList<>(products);
    }

    public List<Product> getProducts() {
        return Collections.unmodifiableList(products);
    }

    /**
     * Update inventory at the end of day: update sellIn first, then update quality based on the new sellIn.
     */
    public void updateEndOfDay() {
        for (Product product : products) {
            int newSellIn = product.getSellIn() - 1;
            product.rawSetSellIn(newSellIn);

            if (product.isTheatrePasses()) {
                updateTheatrePasses(product, newSellIn);
            } else {
                updateRegularProduct(product, newSellIn);
            }
        }
    }

    private void updateRegularProduct(Product product, int newSellIn) {
        int changeBeforeExpiry = 2; // as per spec for regular products
        int decrease = (newSellIn <= -1) ? changeBeforeExpiry * 2 : changeBeforeExpiry; // twice as fast if expired
        int newQuality = product.getQuality() - decrease;
        product.rawSetQuality(newQuality);
    }

    private void updateTheatrePasses(Product product, int newSellIn) {
        if (newSellIn < 0) {
            product.rawSetQuality(0); // drops to zero after the play
            return;
        }
        if (newSellIn <= 5) {
            product.rawSetQuality(product.getQuality() + 3);
        } else {
            product.rawSetQuality(product.getQuality() + 1);
        }
    }
}
