package com.argentrose;

import java.util.Objects;

// Generated by Junie powered by gpt-5-2025-08-07

/**
 * Represents a product in the Argent Rose inventory.
 * A product has a description, a sellIn (days remaining to sell), and a quality value.
 */
public class Product {
    private final String description;
    private int sellIn;
    private int quality;

    public Product(String description, int sellIn, int quality) {
        this.description = Objects.requireNonNull(description, "description");
        this.sellIn = sellIn;
        this.quality = quality;
    }

    public String getDescription() {
        return description;
    }

    public int getSellIn() {
        return sellIn;
    }

    public int getQuality() {
        return quality;
    }

    void decreaseSellInByOne() {
        this.sellIn = this.sellIn - 1;
    }

    void setQuality(int newQuality) {
        // enforce bounds 0..50
        this.quality = Math.max(0, Math.min(50, newQuality));
    }

    void increaseQuality(int delta) {
        if (delta <= 0) return;
        setQuality(Math.min(50, this.quality + delta));
    }

    void decreaseQuality(int delta) {
        if (delta <= 0) return;
        setQuality(Math.max(0, this.quality - delta));
    }

    private void quantityBoundsCheck(int newQuality) {
        if (newQuality < 0) newQuality = 0;
        if (newQuality > 50) newQuality = 50;
        // Assign back to parameter is not visible to caller, but we clamp at caller sites.
    }

    boolean isTheatrePasses() {
        return "Theatre Passes".equalsIgnoreCase(description);
    }

    // Package-private helpers for store logic
    void rawSetSellIn(int newSellIn) { this.sellIn = newSellIn; }
    void rawSetQuality(int newQuality) { this.quality = Math.max(0, Math.min(50, newQuality)); }
}
